// <auto-generated />
namespace QuoteOnQuote.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class VotesToAppUser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(VotesToAppUser));
        
        string IMigrationMetadata.Id
        {
            get { return "201706200842091_VotesToAppUser"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
